### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by codekiln** [guanqun/git-punchcard-plot#5]
Please consider backing timezone data out of the data set. I'd like to use this data to find out when to plan infrastructure upgrades or when to plan meetings.

**Comment by guanqun** [comment]
Thank you for your interests. What do you mean by "backing timezone data out of the dataset"? For example, if we have "9:30 -5 timezone", I should simply treat it as "9:30", right?

**Comment by codekiln** [comment]
I'd like to view the punchcard for my whole team in my local time zone. To do this, you'd add the inverse of the GMT offset to the datetime, then convert the datetime to a user-specified time zone.

**Comment by icyflame** [comment]
Hey @codekiln, this is coming (probably) really late, but I opened a PR adding this feature in #7. :smile: Thanks for the idea, it was enlightening to understand all the different time-related modules in Python.

**Comment by icyflame** [comment]
Hey @guanqun, this issue is now fixed. You should perhaps close it. :slightly_smiling_face:
