### ISSUE TITLE
Example use

### ISSUE THREAD

**Issue by richelbilderbeek** [guanqun/git-punchcard-plot#6]
Hi @guanqun, I was happy to found this GitHub and I'd love to see an example use:

When I use `git-punchcard-plot` on this GitHub like this,

```bash
richel@lubuntu:~/GitHubs/git-punchcard-plot$ git punchcard
```

I get this:

```
['git', 'log', '--no-merges', '--author=', '--pretty=format: %aD']
```

Also specifying the author does *something*:

```
richel@lubuntu:~/GitHubs/git-punchcard-plot$ git punchcard author="guanqun"
['git', 'log', '--no-merges', '--author=guanqun', '--pretty=format: %aD']
```

So, how to use `git-punchcard-plot`, for example, on this GitHub like this?

**Comment by guanqun** [comment]
Hi, Thank you for using this. My bad is not documented properly, the usages you mentioned are correct, besides showing the correct git commands, another file called "output.png" would reside in your current directory, check for it. :) This file is what it generates.

**Comment by richelbilderbeek** [comment]
You are right! Thanks! I hope this will encourage you to mention this in the documentation as well :+1:

**Comment by guanqun** [comment]
Sure, I'll add that to the documentation.
